#!/bin/bash

set -euo pipefail

main(){
    bookname=$1
    if [[ ! -d epub ]]; then mkdir epub; fi
    if [[ ! -d mobi ]]; then mkdir mobi; fi
    pushd $bookname

    if [[ ! -e cover_origin.jpg ]]; then
        ## resize
        magick cover.jpg -resize 600x800! cover_new.jpg
        ## resize end

        ## resize and grayscale
        #magick cover.jpg -resize 600x800! -dither FloydSteinberg -colorspace Gray -depth 4 cover_new.jpg
        ## resize and grayscale end

        mv cover.jpg cover_origin.jpg
        mv cover_new.jpg cover.jpg
    fi

    txt2epub generate $1.txt
    # detect return value split success
    if [ $? -ne 0 ]; then
        exit 1
    fi
    kindlegen book/$bookname.epub -c1 -locale zh -dont_append_source
    mv book/*.epub ../epub/
    mv book/*.mobi ../mobi/
    popd
}

[[ "$0" == "$BASH_SOURCE" ]] && main "$@" || true

